app/models/genre.rb
app/models/item.rb
app/models/order_item.rb
db/migrate/20200502033113_create_genres.rb
db/migrate/20200502033535_create_items.rb
db/migrate/20200502040426_create_order_items.rb
test/fixtures/genres.yml
test/fixtures/items.yml
test/fixtures/order_items.yml
test/models/genre_test.rb
test/models/item_test.rb
test/models/order_item_test.rb

create models genres&items with columns

---

app/models/cart_item.rb
app/models/mailing_address.rb
db/migrate/20200502033351_create_cart_items.rb
db/migrate/20200502033652_create_mailing_addresses.rb
test/fixtures/cart_items.yml
test/fixtures/mailing_addresses.yml
test/models/cart_item_test.rb
test/models/mailing_address_test.rb

cart_itemモデル　と mailing-address モデル
作成しましたー！

Create maling and cart_item model

---

app/models/order.rb
db/migrate/20200502040209_create_orders.rb
test/fixtures/orders.yml
test/models/order_test.rb

order-table-create

---

db/migrate/20200502040209_create_orders.rb

change_orderadress_string

---

db/migrate/20200502033351_create_cart_items.rb
db/migrate/20200502033652_create_mailing_addresses.rb

Add mailing&cartitem to notnull

---

db/migrate/20200502042334_add_name_to_customers.rb

add customer's column

---

db/migrate/20200502040209_create_orders.rb

payment_methodとorder_statusにデフォルト0を足しました。
それとnull falseをいれましや。

setting-default-in-ordertable-payment_method+order_status

---

db/migrate/20200502033535_create_items.rb
db/migrate/20200502040426_create_order_items.rb

ジャンル、アイテム、オーダーアイテムカラムにnot null入れました

fix genres&items colums

---

app/models/customer.rb

add to customer hasmany

---

app/models/order.rb

route.in.order

---

app/models/cart_item.rb
app/models/mailing_address.rb

cart_item と mailing_addressにアソシエーションを書きました。

add c_item&m_address to  belongs

---

app/models/genre.rb
app/models/item.rb
app/models/order_item.rb

ジャンル、アイテム、オーダーアイテムmodelにrelationを追加

create relations to genre,item,order_item teble

---

app/assets/javascripts/admin/customers.coffee
app/assets/javascripts/admin/order_items.coffee
app/assets/javascripts/customer/cart_items.coffee
app/assets/javascripts/customer/customers.coffee
app/assets/javascripts/customer/mailing_addresses.coffee
app/assets/stylesheets/admin/customers.scss
app/assets/stylesheets/admin/order_items.scss
app/assets/stylesheets/customer/cart_items.scss
app/assets/stylesheets/customer/customers.scss
app/assets/stylesheets/customer/mailing_addresses.scss
app/controllers/admin/customers_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/customer/cart_items_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customer/mailing_addresses_controller.rb
app/helpers/admin/customers_helper.rb
app/helpers/admin/order_items_helper.rb
app/helpers/customer/cart_items_helper.rb
app/helpers/customer/customers_helper.rb
app/helpers/customer/mailing_addresses_helper.rb
test/controllers/admin/customers_controller_test.rb
test/controllers/admin/order_items_controller_test.rb
test/controllers/customer/cart_items_controller_test.rb
test/controllers/customer/customers_controller_test.rb
test/controllers/customer/mailing_addresses_controller_test.rb

Create controller cart_item

---

app/controllers/admin/gernes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/customer/items_controller.rb

create actions to genres items

---

app/controllers/admin/orders_controller.rb
app/controllers/customer/orders_controller.rb

action+inorder

---

config/routes.rb

ジャンル、オーダーアイテム、カートアイテムのルーティング設定

create genre order_item cart_item routes

---

app/controllers/admin/items_controller.rb
app/views/admin/home/top.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb

admintotandcustomerfoot

---

app/views/layouts/_footer.html.erb
config/routes.rb

changefooter

---

app/controllers/application_controller.rb
app/controllers/customer/cart_items_controller.rb
app/views/customer/_sidebar.html.erb
app/views/customer/home/top.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/layouts/application.html.erb
config/initializers/application_controller_renderer.rb

update header sidebar

---

app/views/customer/_header.html.erb
app/views/customer/home/top.html.erb
app/views/layouts/_footer.html.erb

Footlayout

---

app/controllers/application_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customer/items_controller.rb
app/views/admin/customers/show.html.erb
app/views/admin/items/index.html.erb
app/views/admins/sessions/new.html.erb
app/views/customer/_header.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb

edit devise

---

app/assets/stylesheets/customer/home.scss
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/home_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/customer/home_controller.rb
app/controllers/customer/items_controller.rb
app/controllers/customer/orders_controller.rb
app/views/customer/home/about.html.erb
app/views/customer/home/top.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/customer/orders/confirm.html.erb
app/views/customer/orders/new.html.erb

もうちょっと改善の余地はありそうですが、カートー＞確認画面ー＞注文完了まで動きます！

Pre complete orders little bad ver

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/customer/home.scss
app/assets/stylesheets/customer/items.scss
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/customer/_header.html.erb
app/views/customer/_sidebar.html.erb
app/views/customer/cart_items/index.html.erb
app/views/customer/home/about.html.erb
app/views/customer/home/top.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/customer/orders/index.html.erb
app/views/customer/orders/new.html.erb
app/views/customer/orders/show.html.erb

Improve around customer  Bootstrap

---

app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

adminのitems/newとedit画像の表示以外はやりました。

orderlayout

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/_header.html.erb

fix header

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/customer/items.scss
app/controllers/admin/customers_controller.rb
app/controllers/admin/home_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customer/home_controller.rb
app/controllers/customer/items_controller.rb
app/views/admin/customers/index.html.erb
app/views/admin/home/top.html.erb
app/views/admin/items/index.html.erb
app/views/admin/orders/index.html.erb
app/views/customer/_sidebar.html.erb
app/views/customer/home/top.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/application.rb
config/initializers/kaminari_config.rb

Admin Top and more

---

app/assets/javascripts/cable.js
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

選択画像のプレビューの表記は、
admin/items/new 
assets/javascripts/cable.js
に書いてあります。

admin/items/new & assets/javascripts/cable.js

---

app/assets/stylesheets/customer/orders.scss
app/controllers/customer/mailing_addresses_controller.rb
app/views/customer/_index.html.erb
app/views/customer/home/top.html.erb
app/views/customer/items/_cart.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/customer/mailing_addresses/_form.html.erb
app/views/customer/mailing_addresses/edit.html.erb
app/views/customer/mailing_addresses/index.html.erb
app/views/customer/orders/_index.html.erb
app/views/customer/orders/index.html.erb
app/views/customer/orders/thanks.html.erb

Create partial / Thanks page

---

app/assets/javascripts/search 2.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/search 2.scss
app/controllers/admin/customers_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/search_controller.rb
app/helpers/search_helper 2.rb
app/models/admin.rb
app/models/customer.rb
app/views/customers/sessions/new.html.erb
app/views/layouts/_header.html.erb
app/views/search/_form.html.erb
app/views/search/_search_customer.html.erb
app/views/search/_search_item.html.erb
app/views/search/search.html.erb
config/locales/devise.ja.yml
config/routes.rb
db/schema.rb
test/controllers/search_controller_test 2.rb

admin側の検索機能実装
customer validationの追加

validate_customer

---

app/controllers/admin/customers_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customers/sessions_controller.rb
app/models/item.rb
app/models/order.rb
app/views/admin/customers/edit.html.erb
app/views/customer/customers/edit.html.erb
app/views/customer/home/top.html.erb
app/views/customer/orders/confirm.html.erb

admin/customer カスタマー周りのページにてフラッシュメッセージの追加

fixed customer
